### ISSUE TITLE
Create Retter a new logo

### ISSUE THREAD

**Issue by mzegar** [mzegar/Retter#11]
I'm not a graphic design artist, It would be nice to replace the current logo of Retter

https://github.com/mzegar/Retter
https://play.google.com/store/apps/details?id=com.mzegar.flutterreddit

1. Create a new logo for Retter
2. Update the README of this repo
3. Upload the logo here in the comments for Google Play

**Comment by mayankparida** [comment]
Hey, I would like to work on this. Please could you assign this to me?

**Comment by mzegar** [comment]
Assigned @mayankparida , let me know if you need any information.

Just some nice looking graphic using a nice shade of blue. I would appreciate a few different sizes just incase.

Thanks!

**Comment by mayankparida** [comment]
I have sent a Pull Request regarding App Icon and AppRun Screenshots and Screen record. Please do check.
