### ISSUE TITLE
Add drawer to view subreddit info

### ISSUE THREAD

**Issue by mzegar** [mzegar/Retter#17]
1. Add a button to view the subreddit info
2. When clicking on this button, a drawer will pop up from the right, displaying the subreddit drawer info

**Comment by bigblackclock** [comment]
I have built the button and the EndDrawer but where do I get the subreddit info, the getter currentSubreddit.infoParams is returning null

**Comment by mzegar** [comment]
DRAW is similar to PRAW, so this link might help you out.

https://old.reddit.com/r/redditdev/comments/5so6rj/praw_find_all_of_a_subreddits_information/
